baseURL = "http://isaaclyman.com/blog"
title = "Minimum Viable Blog"
copyright = "© 2017 by Isaac Lyman. Site powered by Hugo and GitHub Pages."
publishDir = "docs"

theme = "minimo"

googleAnalytics = "G-QX2T3WXRC9"
Paginate = 5
PaginatePath = "archive"

preserveTaxonomyNames = true

pygmentsStyle = "colorful"
pygmentsCodeFences = "true"

ignoreErrors = ["error-remote-getjson"]
cleanDestinationDir = true

[params]
  description = "Software construction, opinion, and self"
  dateFormat = "Jan 2, 2006"
  copyrightOwner = "Isaac Lyman"
  copyrightStartYear = "2017"
  favicon = "favicon.png"
  hideEntryNavigation = false
  customCSS = ["css/custom.css", "css/print.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[taxonomies]
  category = "categories"
  tag = "tags"

# [social]
#  facebook = ""

[params.author]
  name = "Isaac Lyman"

[params.author.email]
  username = "blog"
  host = "isaaclyman.com"

[params.author.social]
  mastodon = "@isaaclyman"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "{ Archive }"
  weight = 10
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "{ Contact }"
  weight = 20
  identifier = "contact"
  url = "/posts/introduction"

[[menu.main]]
  name = "{ RSS }"
  weight = 40
  identifier = "rss"
  url = "/index.xml"


# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en.params]
    lang = "en"
    languageName = "English"
    weight = 1

[markup.goldmark.renderer]
unsafe= true

[markup.highlight]
  style = 'dracula'